name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Backend to EC2
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup SSH Key
      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Step 3: Deploy to EC2
      - name: Deploy Backend to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << EOF
            echo "Navigating to backend directory..."
            cd /home/ubuntu/proximity-backend || exit 1
            
            echo "Pulling latest code from GitHub..."
            git pull origin main

            echo "Exporting environment variables for .env file..."
            export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            export JWT_SECRET=${JWT_SECRET}
            export AWS_REGION=${AWS_REGION}

            echo "Creating/updating .env file..."
            echo "AWS_ACCESS_KEY_ID=\$AWS_ACCESS_KEY_ID" > .env
            echo "AWS_SECRET_ACCESS_KEY=\$AWS_SECRET_ACCESS_KEY" >> .env
            echo "JWT_SECRET=\$JWT_SECRET" >> .env
            echo "AWS_REGION=\$AWS_REGION" >> .env

            echo "Rebuilding Docker container..."
            sudo docker stop backend-container || true
            sudo docker rm backend-container || true
            sudo docker build -t proximity-backend .
            sudo docker run -d --env-file .env -p 3000:3000 --name backend-container proximity-backend
            
            echo "Deployment complete!"
          EOF
